spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  application:
    name: OAUTH-SOCIAL-LOGIN


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 419339224930-ufh59k2j5scvq3dr78i6qv296iecbge6.apps.googleusercontent.com
            client-secret: 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



#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 419339224930-ufh59k2j5scvq3dr78i6qv296iecbge6.apps.googleusercontent.com
#            client-secret: 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
#            scope: profile, email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: Google
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#          github:
#            client-id: YOUR_GITHUB_CLIENT_ID
#            client-secret: YOUR_GITHUB_CLIENT_SECRET
#            scope: read:user, user:email
#            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            client-name: GitHub
#            client-authentication-method: post
#            authorization-grant-type: authorization_code
#        provider:
#          google:
#            authorization-uri: https://accounts.google.com/o/oauth2/auth
#            token-uri: https://oauth2.googleapis.com/token
#            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
#            user-name-attribute: sub
#          github:
#            authorization-uri: https://github.com/login/oauth/authorize
#            token-uri: https://github.com/login/oauth/access_token
#            user-info-uri: https://api.github.com/user
#            user-name-attribute: id
